[resnet34]
learning_rate = 0.01
optimizer = "Adam"
momentum = 0.9

[resnet50]
learning_rate = 0.001
optimizer = "SGD"
momentum = 0.5

[resnet101]
learning_rate = 0.0001
optimizer = "Adam"
momentum = 0.9

[resnet152]
learning_rate = 0.0001
optimizer = "SGD"
momentum = 0.9